---
title: "Assignment 2"
author: "Anita Kurm"
date: "3/11/2020"
output: html_document
---

# Set-up
```{r}
pacman::p_load(extraDistr, R2jags)
source("/Users/anitakurm/Desktop/Masters 2nd semester/Cognitive-Modelling/Module 1/quick_n_clean_plots.R")
source("agents.R")
```


# Rescorla-Wagner Q-learning vs Choice Kernel model
Evaluate the Q-learning model by comparison to the choice kernel model.

(parameter and model recovery)



## Task environment innitiation

```{r}
ntrials <- 100

Aprob <- .3
Arew <- 2

Bprob <- .8
Brew <- 1

#generate a payoff matrix
payoff <- cbind(rbinom(ntrials, 1, Aprob) * Arew, rbinom(ntrials, 1, Bprob) * Brew) #why rbinom?

```

## Model evaluation
very messy at the moment, clean up and make choices using notations by Kenneth or Maris
```{r}
n_simulations = 50


confusion_df <- data.frame() # creates an emmpty data frame

for (i in 1:n_simulations) {
  

  #simulate RW model data
  alpha = 
  beta = 
    
  rw_data_sim = rw(payoff, alpha, beta)
  
  #recover parameters
  
  
  #simulate choice_kernel
  
  alpha = 
  beta = 
  kernel_sims = choice_kernel(payoff, alpha, beta)
  
  
  #recover parameters
  
  
  #-----------run inference RW model to RW data
  
  #data and params

  #jags
  samples <- jags(data, inits = NULL, params,  
                model.file = "rw_jags.txt",
                n.chains = 3, n.iter = 5000, n.burnin = 1000, n.thin = 1) #you average over the sampling chains, 3 is normal, don't go below 3


  DIC.rwm_rwd <- samples$BUGSoutput$DIC 
  
  
  #-----------run inference CK model to RW data
  
  #data and params
  choices <- kernel_sims$choices
  reward <- kernel_sims$reward
  n_trials <- kernel_sims$

  data <- list("choices", "reward", "n_trials")
  params <- c("a", "beta")

  #jags
  samples <- jags(data, inits = NULL, params,  
                model.file = "choice_kernel_jags.txt",
                n.chains = 3, n.iter = 5000, n.burnin = 1000, n.thin = 1) #you average over the sampling chains, 3 is normal, don't go below 3

  DIC.ckm_rwd <- samples$BUGSoutput$DIC 
  
  
  #-----------run inference CK model to CK data
  
  #data and params


  #jags
  samples <- jags(data, inits = NULL, params,  
                model.file = "choice_kernel_jags.txt",
                n.chains = 3, n.iter = 5000, n.burnin = 1000, n.thin = 1) #you average over the sampling chains, 3 is normal, don't go below 3


  DIC.ckm_ckd <- samples$BUGSoutput$DIC
  
  
  #-----------run inference RW model to CK data

  #data and params

  #jags
  samples <- jags(data, inits = NULL, params,  
                  model.file = "rw_jags.txt",
                n.chains = 3, n.iter = 5000, n.burnin = 1000, n.thin = 1) #you average over the sampling chains, 3 is normal, don't go below 3


  DIC.rwm_ckd <- samples$BUGSoutput$DIC 
  
  #-------------write result down
  data_frame <- data.frame("ID" = i,DIC.rwm_rwd, DIC.ckm_rwd, DIC.ckm_rwd, DIC.ckm_ckd)
  confusion_df <- rbind(confusion_df, data_frame)
  
}
```


